version: "3"

services:
  jupyter:
    image: jupyterlab:latest
    ports:
      - 8888:8888
    volumes:
      - my_volume:/project
    environment:
      JUPYTER_TOKEN: "docker"
    build: . 
volumes:
  my_volume:
    external: true